[package]
name = "wtf_is_tcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
etherparse = "0.13.0"
lazy_static = "1.4.0"
tun-tap = "0.1.4"
